language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.4
  - 2.3.0
branches:
  only:
    - master
before_install:
- "./spec/support/before_install.sh"
notifications:
  irc:
    channels:
      - "irc.freenode.net#jovelabs"
    use_notice: true
    skip_join: true
